### Get all users
GET http://localhost:4004/competition/User

### Add a new User

POST http://localhost:4004/competition/User
Content-Type: application/json

{
"ID":20,
"firstName":"Ion",
"lastName":"Popescu",
"age": 20,
"city":"Bucuresti",
"country":"Romania"
}